FROM openjdk:8

# 设置工作目录
WORKDIR /app

ARG JAR_FILE=./target/eladmin-system-1.1.jar
COPY ${JAR_FILE} app.jar

# 设置时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 暴露端口
EXPOSE 8080

# 启动应用
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=prod"]